development:
  clients:
    default:
      database: complex_span_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: complex_span_test
      hosts:
        - localhost:27017
production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
